version: "3.9"

services:
  postgres_client:
    image: postgres:15
    container_name: postgres_client
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CLIENT_SERVICE_DB_NAME}
      POSTGRES_USER: ${CLIENT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${CLIENT_SERVICE_DB_PASSWORD}
    ports:
      - "${CLIENT_SERVICE_DB_PORT}:5432"
    volumes:
      - postgres_client_data:/var/lib/postgresql/data
    networks:
      - banka-network

#  client-service:
#    build:
#      context: ..
#      dockerfile: client-service/Dockerfile
#    container_name: client-service
#    restart: unless-stopped
#    depends_on:
#      - postgres_client
#    environment:
#      CLIENT_SERVICE_PORT: ${CLIENT_SERVICE_PORT}
#      CLIENT_SERVICE_DB_HOST: ${CLIENT_SERVICE_DB_HOST}
#      CLIENT_SERVICE_DB_PORT: ${CLIENT_SERVICE_DB_PORT}
#      CLIENT_SERVICE_DB_NAME: ${CLIENT_SERVICE_DB_NAME}
#      CLIENT_SERVICE_DB_USER: ${CLIENT_SERVICE_DB_USER}
#      CLIENT_SERVICE_DB_PASSWORD: ${CLIENT_SERVICE_DB_PASSWORD}
#      RABBITMQ_HOST: ${RABBITMQ_HOST}
#      RABBITMQ_PORT: ${RABBITMQ_PORT}
#      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
#      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
#      NOTIFICATION_QUEUE: ${NOTIFICATION_QUEUE}
#      NOTIFICATION_EXCHANGE: ${NOTIFICATION_EXCHANGE}
#      NOTIFICATION_ROUTING_KEY: ${NOTIFICATION_ROUTING_KEY}
#      JWT_SECRET: ${JWT_SECRET}
#    ports:
#      - "${CLIENT_SERVICE_DOCKER_PORT}:${CLIENT_SERVICE_PORT}"
#    networks:
#      - banka-network

volumes:
  postgres_client_data:

networks:
  banka-network:
    driver: bridge
